site_name: My Docs
nav:
  - Introduction: index.md
  - Placeholders: 01_placeholders.md
  - Following Steps: 02_follow_steps.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js