site_name: Understanding Technical Documentation
nav:
  - Introduction: index.md
  - Placeholders: 01_placeholders.md
  - Following Steps: 02_follow_steps.md
  - Troubleshooting: 03_troubleshooting.md
  - Basic Structure: 04_basic_structure.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js